// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7PIeZjnLVPaZAyBx1rSeyL9GwUM6KI08',
    appId: '1:744009806802:web:a44e6bb6186245e14c4e0b',
    messagingSenderId: '744009806802',
    projectId: 'tutorial-flutter-henri',
    authDomain: 'tutorial-flutter-henri.firebaseapp.com',
    storageBucket: 'tutorial-flutter-henri.appspot.com',
    measurementId: 'G-6D5VG9QX2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsvU7jov6GpI0v7u9XMMTTQxe81GlO-mI',
    appId: '1:744009806802:android:d429c7ee10ef50b34c4e0b',
    messagingSenderId: '744009806802',
    projectId: 'tutorial-flutter-henri',
    storageBucket: 'tutorial-flutter-henri.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcaiRDCtIVOF1Ig7orpVZKsqtJwmRH2fs',
    appId: '1:744009806802:ios:3125ad4eefee46584c4e0b',
    messagingSenderId: '744009806802',
    projectId: 'tutorial-flutter-henri',
    storageBucket: 'tutorial-flutter-henri.appspot.com',
    iosClientId: '744009806802-3u2g5iqjn8so5lt1gu845dh3gblputg1.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutorial',
  );
}
